USE data_ucb




CREATE TABLE PELICULAS(
ID			INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
DIRECTOR	VARCHAR(45) NOT NULL,
NOMBRE		VARCHAR(196) NOT NULL,
GENERO		VARCHAR(15) NOT NULL,
);

INSERT INTO PELICULAS (DIRECTOR, NOMBRE, GENERO)
VALUES ('JAMES CAMERON', 'AVATAR', 'CIENCIA FICCION')


CREATE TABLE HORARIO(
ID				INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
FECHA_INICIO	DATETIME NOT NULL,
FECHA_FIN		DATETIME NOT NULL,
ID_PELICULA		INT NOT NULL FOREIGN KEY REFERENCES PELICULAS (ID)
);

INSERT INTO HORARIO (FECHA_INICIO, FECHA_FIN, ID_PELICULA)
VALUES (GETDATE(), GETDATE()+10, 1)



CREATE TABLE SALA(
ID			INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
NOMBRE		VARCHAR(50) NOT NULL,
UBICACION	VARCHAR(5) NOT NULL,
ID_HORARIO	INT NOT NULL FOREIGN KEY REFERENCES HORARIO (ID)
);

INSERT INTO SALA (NOMBRE, UBICACION, ID_HORARIO)
VALUES ('SALA 2', 'A1', 1)


SELECT * FROM PELICULAS
SELECT * FROM HORARIO
SELECT * FROM SALA
